### ISSUE TITLE
Very noisy boundaries using boundary loss

### ISSUE THREAD

**Issue by tom725** [yiskw713/boundary_loss_for_remote_sensing#1]
Hi, thanks for your implementation !

I use boundary loss (+ cross entropy +lovasz loss) to train a UNET model to find buildings in remote sensing images
I get these strange noisy boundaries as a result and don't know what's going on. 
Did you ever get this kind of result ? 
![noisy_boundaries](https://user-images.githubusercontent.com/5737180/69252537-72206a80-0bb3-11ea-86f7-2f4049df72f3.PNG)

For comparison, below is the same result but only with cross entropy + lovasz loss:

![lovasz_boundaries](https://user-images.githubusercontent.com/5737180/69252971-24583200-0bb4-11ea-8846-87673a05b602.PNG)

Thanks !

**Comment by yiskw713** [comment]
thmscll

Thank you for visiting my repo.
And sorry for the delay in replying.

Actually, I haven't tried semantic segmentation using this boundary loss yet.
I used this loss for action segmentation but it did not work well.

**Comment by Hellomodo** [comment]
Applying F.max_pool2d to pred makes the model fall into a local minum of jagged mask edges，I guess.
